Peersyst/near-mobile-wallet

- package.json
- yarn.lock
closes #77 
* Install react-native-view-pager explicitly, otherwise ios doesn't find RNCViewPager
> fix pager view ios crash

- src/module/main/component/navigation/MainTabs/MainTabs.tsx
- test/__mocks__/common/wallet/index.tsx
- test/__mocks__/common/wallet/useWalletGradient.mock.ts
- test/unit/src/module/main/component/navigation/MainTabs/MainTabs.spec.tsx
closes #234 
- MainTabs (calling useWalletGradient to get the colors) + test
- useWalletGradient.mock.ts (Created necessary mock for MainTabs test)
> Change tab indicator color based on selectedWallet

- src/locale/locales/en/common.json
- src/locale/locales/es/common.json
- src/locale/locales/fr/common.json
- src/locale/locales/id/common.json
- src/locale/locales/it/common.json
- src/locale/locales/pt/common.json
- src/locale/locales/ru/common.json
- src/locale/locales/uk/common.json
- src/locale/locales/vi/common.json
- src/locale/locales/zh-CN/common.json
- src/locale/locales/zh-TW/common.json
- src/module/signer/components/display/SignRequestDetails/actions.tsx
- src/module/signer/components/display/SignRequestDetails/actions.types.ts
- src/module/signer/components/display/SignRequestDetails/actions/DeleteKeyDetails.tsx
- src/module/signer/queries/useAddKeyAction.ts
- src/module/signer/queries/useDeleteAccessKey.ts
- src/module/signer/queries/useSignRequestActions.ts
- test/unit/src/module/signer/components/display/SignRequestDetails/actions/DeleteKeyDetails.spec.tsx
- [[TA-1151] DeleteKey (details modal + action approval)](https://www.notion.so/DeleteKey-details-modal-action-approval-6c7ec3a8476c437e82ae7610cc0c1bbb?pvs=4)
- `DeleteKeyDetails` modal details component
- `useDeleteAccessKey` query
- updated `useSignRequestActions` supporting deleteKey actions
- locale update
- testing
> [TA-1151] DeleteKey (details modal + action approval)

- src/config/configs/config.base.json
- src/config/configs/config.dev.json
- [[TA-1234] Remove not supported sites from config](https://www.notion.so/Remove-not-supported-sites-from-config-8bfb0b28c14f4860b22d8a3853ab1f73?pvs=4)
- deleted `RainbowBridge` and `Jump Defi` dapps from config
> [TA-1234] Remove not supported sites from config

- src/config/config.tsx
- src/module/signer/components/display/FunctionCallPermissions/FunctionCallPermissions.tsx
- src/module/signer/components/display/SignRequestDetails/actions/FunctionCallDetails.tsx
- src/module/signer/components/display/SignRequestDetails/actions/StakeDetails.tsx
- src/module/signer/components/display/SignRequestDetails/actions/TransferDetails.tsx
- [[TA-1207] Add contract blockchain links](https://www.notion.so/Add-contract-blockchain-links-a868319332904f8fb1d551abd893ac77?pvs=4)
- Added `BlockchainAddress` component in smart contract id fields
- fixed explorer link due to changes (`address` -> `accounts`)
- `StakeDetails` missing refactor with `ActionDetailField`
> [TA-1207] Add contract blockchain links

- src/module/signer/components/display/ActionsSlider/ActionsSlider.styles.ts
- src/module/signer/components/display/ActionsSlider/ActionsSlider.tsx
- src/module/signer/components/layout/SignatureScaffold/SignatureScaffold.tsx
- [[TA-1238] Fix ActionSlider dots to primary](https://www.notion.so/Fix-ActionSlider-dots-to-primary-72b854a6ad994d8ba32b54e7d3feadae?pvs=4)
- `ActionsSliderRoot` styled component
- updated `ActionsSlider` with new styled component
> [TA-1238] Fix ActionSlider dots to primary

- src/config/configs/config.dev.json
- src/locale/locales/en/errors.json
- src/locale/locales/es/errors.json
- src/locale/locales/fr/errors.json
- src/locale/locales/id/errors.json
- src/locale/locales/it/errors.json
- src/locale/locales/pt/errors.json
- src/locale/locales/ru/errors.json
- src/locale/locales/uk/errors.json
- src/locale/locales/vi/errors.json
- src/locale/locales/zh-CN/errors.json
- src/locale/locales/zh-TW/errors.json
- src/module/signer/components/display/ActionsSlider/ActionsSlider.tsx
- src/module/signer/components/display/SignRequestDetails/SignRequestDetails.tsx
- src/module/signer/components/layout/SignatureScaffold/SignatureScaffold.tsx
- src/module/signer/containers/SignerMessageModal/SignerMessageModal.tsx
- src/module/signer/containers/SignerRequestModal/SignerRequestModal.tsx
- src/module/signer/containers/SignerRequestModal/hooks/useHandleSigneRequestError.tsx
- [[TA-1237] SignerId missmatch error](https://www.notion.so/SignerId-missmatch-error-6c1fc095e94a4103acb2cdfb0bdcb605?pvs=4)
- `useHandleSignerRequestError` hook to handle possible errors (such as `network` or `signerId` mismatches)
- Updated `SignerRequestModal` with error handling
- updated errors locale
> [TA-1237] SignerId missmatch error

- src/locale/locales/en/common.json
- src/locale/locales/es/common.json
- src/locale/locales/fr/common.json
- src/locale/locales/id/common.json
- src/locale/locales/it/common.json
- src/locale/locales/pt/common.json
- src/locale/locales/ru/common.json
- src/locale/locales/uk/common.json
- src/locale/locales/vi/common.json
- src/locale/locales/zh-CN/common.json
- src/locale/locales/zh-TW/common.json
- src/module/signer/components/display/SignMessageDetails/SignMessageDetails.tsx
- src/module/signer/components/layout/SignatureScaffold/SignatureScaffold.tsx
- src/module/signer/containers/SignerMessageModal/SignerMessageModal.tsx
- src/module/signer/containers/SignerRequestModal/SignerRequestModal.tsx
- src/module/signer/containers/SignerWalletSelector/SignerWalletSelector.tsx
- src/module/signer/context/SignerModalContext.ts
- src/module/signer/queries/useIsActiveAccount.ts
- src/module/signer/queries/useSignMessage.ts
- src/query/queries.ts
- [[TA-1250] Handle inactive accounts](https://www.notion.so/Handle-inactive-accounts-d1143b4c627c4a78857e187d829a260d?pvs=4)
- `useIsActiveAccount` query to check if an account is activated or not
- `SignatureScaffold` handles account activation
- renaming on `SignerModalContext` (due to usage on both modals)
- locale updates
> [TA-1250] Handle inactive accounts

- src/config/configs/config.staging.json
- src/module/signer/components/feedback/DisconnectableDApp/DisconnectableDApp.tsx
- src/module/signer/components/feedback/DisconnectableDApp/hooks/useDisconnectDAppDialog.tsx
- [[TA-1368] Dialog not loading or disabled buttons when disconnect](https://www.notion.so/Dialog-not-loading-or-disabled-buttons-when-disconnect-87526148859b4625a80108d03838b76d?pvs=4)
#363 
- `useDisconnectDAppDialog` to control dialog because `loading` & `disabled` props not working with `useDialog` hook
- `config.staging` enabledChangeNetwork to test signature with testnet network
> [TA-1368] Dialog not loading or disabled buttons when disconnect

- src/module/home/screen/HomeScreen.tsx
- [[TA-1369] Check Deep linking render](https://www.notion.so/Check-Deep-linking-render-7731e8a7a207433f857208bf7417ed83?pvs=4)
- Updated useEffect in HomeScreen to trigger `showSignerRequest` when appState is `active`
**Previous problem**: When the app was not open or in background deep linking was working fine. But if the app was in background state and a QR code was scanned and the user was redirected to the app, the SignerModal was not showing
https://github.com/Peersyst/near-mobile-wallet/assets/68080871/d566c536-463e-460d-92c5-03542c55f0a3
> [TA-1369] Check Deep linking render

- package.json
- yarn.lock
- [[TA-1401] Withdraw staking crashes the app](https://www.notion.so/Withdraw-staking-crashes-the-app-9d55034de6874547adc31e4cc0ee885c?pvs=4)
- removed `bn.js` version dependency (5.2.1 version was crashing on `useGetWithdrawValidators` -> `BalanceOperations)` to default version `5.2.0`
> [TA-1401] Withdraw staking crashes the app

- src/module/staking/hook/useGetWithdrawValidators.ts
- Updated BalanceOperations method from `BNIsBigger` to `isBigger` in `useGetWithdrawValidators`
> [FIX]: Withdraw error

- src/module/sdk/NearSdkService/NearSdkService.ts
- test/unit/src/module/transaction/component/input/AddressTextField.spec.tsx
- `NearSdkService` instead of checking that only `mainnet` or `testnet` is valid, check that `testnet` is not using in mainnet and viceversa. This way, we support all suffixes.
> [TA-2166] Support .tg addresses

- src/index.tsx
- src/module/common/component/feedback/Actionable/Actionable.tsx
- src/module/signer/components/display/DApp/DApp.tsx
- Add `GestureHandlerRootView` to `index.tsx` to enable all `react-native-gesture-handler` features. Such as `Swipeable` not triggering `Touchable` `onPress`
- Make all the `Actionable` pressable instead of the `action` exclusively
- Change `TouchableOpacity` import in `DApp` from `react-native` to `react-native-gesture-handler`
> [TA-2169] Swipe DApp to disconnect

- src/module/wallet/hook/useImportWallets.ts
- src/module/wallet/hook/useRecoverWallets.ts
- src/module/wallet/utils/WalletController.ts
- Remove checks when having 0 wallets in a mnemonic (not possible nevertheless).
- When recovering wallets after deinstalation, old wallets are recovered sucessfully but the following warning appears: `"Corrupted storage: Wallet not found. WalletId: ", walletId`
> [TA-2201] Fix recover wallets

- package.json
- src/module/sdk/utils/BalanceOperations.ts
- src/module/sdk/utils/near.utils.ts
- yarn.lock
- Use `parseFloat` instead of `BigInt` in `BNDevide`
> [TA-2249] Fix token decimals display

- src/module/sdk/NearApiService/NearBlocksService.ts
- Add an `if` statement to check the `predecessor_account_id` of a transaction in `NearBlocksService` to exclude `system` transactions
> [TA-2258] Remove `system` transactions

- src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts
- src/module/sdk/NearSdkService/NearSdkService.ts
- [Validator 0 staked amount when it has > 0](https://www.notion.so/1930f38fb1e94f82845dab04ac1caeca?v=64f1d5da841741cf9cb3b831e5b493e3&p=d5e0adb3750d49028baf853b550c5316&pm=s)
- Return all possible validators in API call
- Filter validators with 0 amount in get current validators
> [TA-2359] Fix Validator 0 staked amount when it has > 0

- CHANGELOG.md
- src/module/nft/component/display/NftImage/NftImage.styles.ts
- src/module/sdk/NearSdkService/NearSdkService.ts
- src/module/sdk/utils/near.constants.ts
> Fix NFTs not being displayed in the APP

- CHANGELOG.md
- src/module/signer/components/display/ActionsSlider/ActionsSlider.tsx
- src/module/signer/containers/SignerRequestModal/SignerRequestModal.tsx
-  When trying to scroll to see multiple actions in the signer request modal it does not work.
-   Add a the prop `onStartShouldSetResponder` to the PagerView
> Fix SignerRequestModal not scrolling on android

- CHANGELOG.md
- src/module/common/component/feedback/LoadingLogo/LoadingLogo.styles.ts
- src/module/common/component/feedback/LoadingLogo/LoadingLogo.tsx
- src/module/common/component/feedback/LoadingLogo/LoadingLogo.types.ts
- src/module/common/component/feedback/LoadingModal/LoadingModal.styles.ts
- src/module/common/component/feedback/LoadingModal/LoadingModal.tsx
- src/module/dapp/screen/BrowserScreen/BrowserScreen.styles.tsx
- src/module/dapp/screen/BrowserScreen/BrowserScreen.tsx
- DApps browser view was not loading with the right height in iOS
- Refactor loadings with logo adding `LoadingLogo`
- Handle loading correctly in `BrowserScreen` by showing a loading screen while the web view is loadinh
-   [dev](https://github.com/Peersyst/near-mobile-wallet)
> Fix dapps webview loading

- CHANGELOG.md
- app.config.ts
- src/config/configs/config.base.json
- src/locale/locales/en/common.json
- src/locale/locales/en/errors.json
- src/locale/locales/es/common.json
- src/locale/locales/es/errors.json
- src/locale/locales/fr/common.json
- src/locale/locales/fr/errors.json
- src/locale/locales/id/common.json
- src/locale/locales/id/errors.json
- src/locale/locales/it/common.json
- src/locale/locales/it/errors.json
- src/locale/locales/pt/common.json
- src/locale/locales/pt/errors.json
- src/locale/locales/ru/common.json
- src/locale/locales/ru/errors.json
- src/locale/locales/sw/common.json
- src/locale/locales/sw/errors.json
- src/locale/locales/uk/common.json
- src/locale/locales/uk/errors.json
- src/locale/locales/vi/common.json
- src/locale/locales/vi/errors.json
- src/locale/locales/zh-CN/common.json
- src/locale/locales/zh-CN/errors.json
- src/locale/locales/zh-TW/common.json
- src/locale/locales/zh-TW/errors.json
- src/module/common/query/useLoad.ts
- Fix `android` backup data bug freezing the app when reinstalling it.
- https://docs.expo.dev/versions/v52.0.0/sdk/securestore/#android-auto-backup
- https://github.com/expo/expo/issues/23426
- Handle backed up data decryption error in `useLoad` and remove secure storage data to starts fresh.
- [Dev](https://github.com/Peersyst/near-mobile-wallet)
> Fix `android` backup data bug
