app.config.ts, src/Navigator.tsx, src/Stack.ts, src/config/theme/darkTheme.ts, src/config/theme/lightTheme.ts, src/config/theme/theme.declarations.d.ts, src/module/common/component/input/Select/Select.styles.ts, src/module/common/component/layout/BaseSecondaryScreen/BaseSecondaryScreen.styles.ts, src/module/common/component/layout/BaseSecondaryScreen/BaseSecondaryScreen.tsx, src/module/common/component/layout/Toolbar/Toolbar.styles.ts, src/module/common/component/navigation/Header/Header.tsx, src/module/common/component/navigation/MainNavigatorGroup/MainNavigatorGroup.tsx, src/module/common/component/navigation/MainNavigatorGroup/MainScreens.ts, src/module/common/component/navigation/Navbar/Navbar.tsx, src/module/main/component/layout/BaseMainScreen/BaseMainScreen.styles.ts, src/module/main/component/layout/BaseMainScreen/BaseMainScreen.tsx, src/module/main/component/navigation/MainBottomNavigatorGroup/MainBottomNavigatorGroup.tsx, src/module/main/component/navigation/MainBottomNavigatorGroup/MainBottomNavigatorGroup.types.ts, src/module/settings/components/navigation/SettingsNavigatorGroup/SettingsNavigatorGroup.tsx, src/module/settings/screen/GeneralSettingsScreen.tsx, src/module/settings/screen/SecuritySettingsScreen.tsx, src/module/settings/screen/SettingsScreen.tsx, test/unit/src/module/common/component/layout/SecondaryPage.spec.tsx, test/unit/src/module/common/component/navigation/Header/Header.spec.tsx, test/unit/src/module/settings/screen/SecuritySettingsScreen.spec.tsx, test/unit/src/module/settings/screen/SettingsScreen.spec.tsx
#79 
* Refactor navigation to hide header on settings
* Also didn't make sense to have everything on the same bottom tab navigator
* Please fix SettingsScreen.spec
=> Settings navigation refactor

src/module/wallet/navigator/ImportWalletNavigatorGroup.tsx
closes #95 
- ImportWalletNavigatorGroup
- Removed SET_WALLET_NAME enum
- Removed SET_WALLET_NAME tab
- Number of tabs updated
=> ImportWallet order

src/module/common/service/NearSdkService.ts, src/module/common/service/NearSdkService.types.ts
**Tasks:**
- Add transaction return type
- Type transaction action args
=> add types file and type transaction return

src/module/wallet/WalletStorage.ts, test/__mocks__/storage/walletStorage.mock.ts, test/unit/src/module/transaction/hook/useUpdateUncommitedTransactions.spec.ts
=> Remove initial state

src/config/config.base.json, src/config/config.declarations.d.ts, src/config/config.dev.json, src/config/config.prod.json, src/config/config.staging.json, src/config/config.tsx, src/module/common/component/input/Select/Select.styles.ts, src/module/common/component/input/TextField/TextField.styles.ts, src/module/common/query/useLoad.ts, src/module/settings/components/core/SelectNetwork/SelectNetwork.tsx, src/module/settings/state/SettingsState.ts, test/__mocks__/genesys/useConfig/useConfig.mock.ts, test/unit/src/module/common/query/useLoad.spec.ts, test/unit/src/module/settings/core/SelectNetwork.spec.tsx
- closes #171 
- dev, #172 
- Do not enable mainnet
- Some tests improvements =)
=> Settings - Do not enable mainnet

package.json, src/locale/locales/en/common.json, src/locale/locales/es/common.json, src/module/nft/component/display/NftCard/NftCard.tsx, test/unit/src/module/nft/component/display/NftCard/NftCard.spec.tsx, yarn.lock
closes #108
#175
- Update NftCard
- Update lib to fix infinity image loading
=> NFTs List 

package.json, yarn.lock
closes #236 
#
- upgrade react-native-components
=> change version react-native-components

src/module/sdk/NearSdkService/NearSdkService.ts
- Crec que no hi ha issue feta (està al slack)
- Wait promise on nfts before parsing
=> fix error on mintbase nfts with metadata

src/config/globalStyles.ts, src/module/common/component/feedback/LoadingModal/LoadingModal.tsx, src/module/wallet/component/input/WalletSelectorGroup/AccountSelector.tsx
- closes #280
- closes #281
- dev
- Add LoadingSpinner in Loader
- Improve visibility of account in selector
=> Acc visibility in selector + spinner in tx

src/module/wallet/component/input/MnemonicInput/MnemonicInput.tsx, test/unit/src/module/wallet/component/input/MnemonicInput/MnemonicInput.spec.tsx
- Enable copy & paste in the mnemonic
=> Enable Copy&Paste of the mnemonic

src/module/sdk/utils/near.utils.ts
=> fix number formatting

src/locale/locales/es/common.json
=> Fix spanish send locale

src/module/fiatorders/components/core/BuyWithTransak/hook/useTransakOnRamp.tsx, src/module/fiatorders/components/core/BuyWithTransak/hook/useTransakOnRampQueryParams.tsx, src/module/transak/TransakWebView/TransakWebView.tsx, src/module/transak/TransakWebView/TransakWebView.types.tsx, src/module/transak/TransakWebView/utils/parseQueryParams.tsx
- Parse transak queryParams
- Remove event tracker in `Transak`
=> feat(transak): parse query params

src/module/common/component/layout/BasePage/BasePage.styles.ts, src/module/common/component/layout/BasePage/BasePage.tsx, src/module/common/component/layout/BasePage/BasePage.types.ts, src/module/common/component/navigation/MainNavigatorGroup/MainNavigatorGroup.tsx, src/module/fiatorders/components/navigation/FiatOrdersNavigatorGroup/FiatOrdersNavigatorGroup.tsx, src/module/wallet/component/core/WalletsBackupModal/WalletPrivateKeyBackup/WalletPrivateKeyBackup.tsx, src/module/wallet/component/input/BlockchainAddressCard/BlockchainAddressCard.styles.tsx, src/module/wallet/component/input/BlockchainAddressCard/BlockchainAddressCard.tsx, src/module/wallet/component/input/WalletSelectorGroup/AccountSelector.tsx
[BlockchainAddress fixes](https://www.notion.so/1930f38fb1e94f82845dab04ac1caeca?v=64f1d5da841741cf9cb3b831e5b493e3&p=c2f11995966f41dda60a34033206671d&pm=s)
- Fix copy private key
- Fix transak modal
=> Private key copy and transak modal

.github/ISSUE_TEMPLATE/FORM_NAME.yml
=> Default Issue Template

src/config/configs/config.prod.json
=> [FIX] Signer backend url

src/locale/locales/en/common.json, src/locale/locales/es/common.json, src/locale/locales/fr/common.json, src/locale/locales/id/common.json, src/locale/locales/it/common.json, src/locale/locales/pt/common.json, src/locale/locales/ru/common.json, src/locale/locales/uk/common.json, src/locale/locales/vi/common.json, src/locale/locales/zh-TW/common.json, src/module/sdk/NearSdkService/NearSdkService.types.ts, src/module/transaction/component/display/ActionIcon/ActionIcon.tsx, src/module/transaction/component/display/ActionIcon/actionIcons.ts, src/module/transaction/component/display/ActionLabel/hooks/useGetActionLabel/useGetActionLabel.ts
- Add default icon to `ActionIcon` to prevent the app crash.
- Add support to `DELEGATE_CALL` tx
=> fix: use get actions fix

src/config/configs/config.base.json, src/config/configs/config.dev.json, src/config/configs/config.prod.json, src/config/configs/config.staging.json, src/config/configs/config.test.json
- updated `recommendedDApps` on all configs
=> [TA-2149] Update dApps list

src/module/sdk/NearApiService/ApiService.ts
=> fix old accounts recovery

src/module/nft/query/useGetNfts.ts, src/module/signer/components/display/DApp/DApp.tsx, src/module/staking/query/useGetTotalStaking.ts, src/module/token/query/useGetTokens.ts, src/module/transaction/query/useSendFT.ts, src/module/transaction/query/useSendNEAR.ts, src/module/transaction/query/useSendNFT.ts, src/module/wallet/component/core/WalletsBackupModal/WalletsBackupAdvise/WalletsBackupAdvise.tsx, src/module/wallet/query/useGetBalance.ts
=> [TA-2248] Add PostHog events

src/module/staking/query/useGetTotalStaking.ts, src/module/token/query/useGetTokens.ts, src/module/transaction/query/useSendFT.ts, src/module/transaction/query/useSendNEAR.ts, src/module/transaction/query/useSendNFT.ts, src/module/wallet/query/useGetBalance.ts
- Parse string to number in PostHog events
=> Fix: parse string to number in PostHog events

src/module/sdk/NearApiService/ApiService.ts, src/module/sdk/NearApiService/NearApiService.types.ts, src/module/sdk/NearApiService/NearBlocksService.ts
=> fix(app): nfts fts fix

src/module/staking/screen/StakingScreen.tsx
=> fix: add alert in staking screens

src/module/sdk/NearApiService/ApiService.ts, src/module/sdk/NearApiService/NearApiService.types.ts, src/module/sdk/NearApiService/NearBlocksService.ts, src/module/sdk/utils/near.constants.ts
- [Staking information is not displayed properly](https://www.notion.so/1930f38fb1e94f82845dab04ac1caeca?v=64f1d5da841741cf9cb3b831e5b493e3&p=7cd34087c2ed4caaaa8e148b9b7cec2b&pm=s)
- Query all staking related transactions and calculate deposited (without withdrawing) amount to compute rewards
- Do not repeat validators to fix staked amount
=> [TA-2255] Fix Staking information is not displayed properly

src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts
- [Fix Staking Negative Rewards](https://www.notion.so/1930f38fb1e94f82845dab04ac1caeca?v=64f1d5da841741cf9cb3b831e5b493e3&p=9351db3f3bea49a59b4d8795139e30bf&pm=s)
- Reset amount when staked amount is negative
=> [TA-2315]: Fix staking negative values

src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts, src/module/sdk/NearSdkService/NearSdkService.ts
- [Fix some cases of invalid staking values](https://www.notion.so/1930f38fb1e94f82845dab04ac1caeca?v=64f1d5da841741cf9cb3b831e5b493e3&p=29fbd21da47d48cbbcb33b8e3b2a22e7&pm=s)
- Discard validator if total amount is 0
- Make sure logs are read correctly. In some situations they were different
=> [TA-2358]: Fix some cases of invalid staking values

src/module/common/component/surface/BaseWalletCard/BaseWalletCard.styles.ts, src/module/common/component/surface/BaseWalletCard/BaseWalletCard.tsx, src/module/wallet/component/display/Account/Account.tsx
closes #
#410 
- Move imported badge in BaseWalletCard and remove in Account
=> [TA-2365] : App(fix) move imported badge in BaseWalletCard

app.config.ts, src/config/configs/config.base.json, src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts
- Change near blocks endpoint
- Handle tx without action edge case
=> [v1.5.2] feat(app): change near blocks endpoint

src/config/config.declarations.d.ts, src/config/configs/config.base.json, src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts, src/module/sdk/NearApiService/NearBlocks/NearBlocksService.types.ts, src/module/sdk/NearSdkService/NearSdkService.ts, src/module/sdk/NearSdkService/NearSdkService.types.ts, src/module/staking/hook/useGetStakingDetailsSections.ts, src/module/wallet/state/ServiceInstances/ServiceInstances.ts, src/module/wallet/state/ServiceInstances/ServiceInstances.types.ts
- Ignore rewards if no logs
- Get logs from archival node when missing
=> flag to ignore rewards if no logs + get logs from archival node

src/module/signer/components/display/DAppStatus/DAppStatus.styles.ts, src/module/signer/components/display/DAppStatus/DAppStatus.tsx, src/module/signer/components/display/DAppStatus/hooks/useDAppStatus.ts
[TA-2451] [APP] feat : Fix gray error
closes #
#
-
=> [TA-2451] [APP] feat : Fix gray error

src/module/transaction/component/core/AddNearModal/AddNearModal.tsx
[APP] feat : add handleOnSupport
closes #
#
-
=> [APP] feat : add handleOnSupport

src/module/transaction/component/input/AssetAmountTextField/AssetAmountTextField.tsx
[TA-2517] [APP] feat : Add Max option in send Near
closes #
#
-
=> [TA-2517] [APP] feat : Add Max option in send Near

src/module/faqs/component/display/FAQ/FAQ.tsx, src/module/faqs/component/display/FAQs/FAQs.tsx
[APP] fix: change typography in faqs
closes #
#
-
=> [APP] fix: change typography in faqs

app.config.ts, src/module/common/component/feedback/AppUpdater/AppUpdater.tsx
=> commit dummy

app.config.ts
Fixs problem expo-updates
closes #
#
-
=> Fixs problem expo-updates

package.json, yarn.lock
downgrade expo-updates
closes #
#
-
=> downgrade expo-updates

src/module/common/hook/useGetSwapLink.ts
=> Fix swapUrl

src/module/transaction/component/core/SendModal/SendModal.tsx
=> Fixs sendModal

src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts, src/module/sdk/NearApiService/NearBlocks/NearBlocksService.types.ts
[APP] fixs: resolved wrong add deposits
closes #
#
-
=> [APP] fixs: resolved wrong add deposits

src/config/config.declarations.d.ts, src/module/signer/utils/near.transactions.ts, src/module/wallet/component/core/ManualAccountImportModal/ManualAccountImportModal.tsx, src/module/wallet/component/core/ManualAccountImportModal/hooks/useManualAccountImportModal.tsx
=> Fix wrong imports making the app crash

src/module/sdk/NearSdkService/NearSdkService.ts, src/module/sdk/utils/near.constants.ts
- Customize gas for withdraw in staking
=> Staking: set gas for withdraw to 200TGas

src/module/sdk/NearApiService/FastNear/FastNearService.ts, src/module/sdk/NearApiService/NearBlocks/NearBlocksService.ts, src/module/sdk/NearApiService/NearBlocks/NearBlocksService.types.ts, src/module/sdk/NearSdkService/NearSdkService.ts, src/module/sdk/NearSdkService/NearSdkService.types.ts
- Change the way the deposits are calculated
=> Migrate to kitwallet in staking

src/module/signer/components/display/DApp/DApp.tsx, src/module/wallet/component/core/WalletCard/WalletCardButtons/WalletCardButtons.tsx
[TA-3065] Add dApp webview handle in Android
closes #
#
-
=> [TA-3065] Add dApp webview handle in Android

CHANGELOG.md, package.json, src/config/config.declarations.d.ts, src/config/configs/config.base.json, src/locale/locales/en/common.json, src/locale/locales/es/common.json, src/locale/locales/fr/common.json, src/locale/locales/id/common.json, src/locale/locales/it/common.json, src/locale/locales/pt/common.json, src/locale/locales/ru/common.json, src/locale/locales/sw/common.json, src/locale/locales/uk/common.json, src/locale/locales/vi/common.json, src/locale/locales/zh-CN/common.json, src/locale/locales/zh-TW/common.json, src/module/settings/components/core/VersionNumber/VersionNumber.tsx, src/module/settings/components/layout/BaseSettingsTab/BaseSettingsTab.styles.ts, src/module/settings/components/layout/BaseSettingsTab/BaseSettingsTab.tsx, src/module/settings/screen/SecuritySettingsScreen.tsx
=> Feat: add version

CHANGELOG.md, package.json, src/providers/Providers.tsx, src/query/RefetchHandler/RefetchHandler.tsx, src/query/RefetchHandler/hooks/useRefetchHandler.ts, yarn.lock
Add a `RefetchHandler` to improve the sync of the balance between the online/offline and the active/background states
=> Refetch handler

CHANGELOG.md, src/module/common/component/navigation/BottomBar/MainBottomBarItem/MainBottomBarItem.tsx, src/module/dapp/DAppsStorage.ts, src/module/dapp/components/display/FavouriteDApp/FavouriteDApp.styles.ts, src/module/dapp/components/display/FavouriteDApp/FavouriteDApp.tsx, src/module/dapp/components/layout/BaseDAppsScreen.tsx, src/module/dapp/containers/FavouritesDApps/FavouritesDApps.styles.tsx, src/module/dapp/containers/FavouritesDApps/FavouritesDApps.tsx, src/module/dapp/containers/FavouritesDApps/FavouritesDAppsSkeletons/FavouritesDAppsSkeletons.tsx, src/module/dapp/screen/DappsScreen/DAppsScreen.tsx, src/module/dapp/screen/DappsScreen/hooks/useDAppsScreen.ts, src/module/main/component/navigation/MainBottomNavigatorGroup/MainBottomNavigatorGroup.tsx
- Fix bottom bar icon color
- Fix added history not being displayed at the top
- Add loading to fav list
- Improve scroll on fav list
=> Explore improvements

CHANGELOG.md, src/config/configs/config.base.json, src/module/dapp/screen/DappsScreen/DAppsScreenCTA/DAppsScreenCTA.tsx, src/module/dapp/screen/DappsScreen/DAppsScreenCTA/hooks/useDAppsExploreLink.ts
=> Update dapps explore link

CHANGELOG.md, src/module/dapp/navigator/DAppsNavigator.tsx, src/module/dapp/screen/BrowserScreen/hooks/useBrowserScreenBrowser.ts
Force webview to unmount
- Fixes:
```
Se queda pillado el Browser en Ref SWAP cuando abres el browser desde Menu Button SWAP o desde Token SWAP (Android)
```
=> Force webview to unmount

CHANGELOG.md, src/config/configs/config.base.json, src/config/configs/config.dev.json, src/config/configs/config.prod.json, src/config/configs/config.staging.json, src/config/configs/config.test.json
-   Update recomended dApps config so their images show at explore page.
-   Added dApps json ✨
-   Warning... ⚠️
-   This part could be improved...
-   [Main](https://github.com/Peersyst/near-mobile-wallet)
=> add new dapps to config base

src/config/configs/config.base.json
-   Briefly describe the issue or motivation for this PR. Include any relevant background information.
-   Describe the 1st change ✨
-   Describe the 2nd change ✨
-   Warning... ⚠️
-   This part could be improved...
-   [Main](https://github.com/Peersyst/near-mobile-wallet)
=> [TA-3667] refactor: update explore url
